/**
 * Travel Data & Reference Catalog
 * VoyageMCP - Open travel knowledge base without commercialized API keys
 */

import {
  DestinationSummary,
  CurrencyRate,
  VisaInfo,
  WeatherSeasonInfo,
  DestinationFactoids,
  FlightOption,
  GroundTransportOption,
  AccommodationOption,
  PlaceActivity,
} from '../types/travel';

export const GLOBAL_CURRENCY_RATES: Record<string, CurrencyRate> = {
  JPY: { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rateAgainstSGD: 114.25, lastUpdated: '2026-09-24' },
  EUR: { code: 'EUR', name: 'Euro', symbol: '€', rateAgainstSGD: 0.692, lastUpdated: '2026-09-24' },
  USD: { code: 'USD', name: 'US Dollar', symbol: '$', rateAgainstSGD: 0.745, lastUpdated: '2026-09-24' },
  GBP: { code: 'GBP', name: 'British Pound', symbol: '£', rateAgainstSGD: 0.585, lastUpdated: '2026-09-24' },
  IDR: { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rateAgainstSGD: 11850.0, lastUpdated: '2026-09-24' },
  KRW: { code: 'KRW', name: 'South Korean Won', symbol: '₩', rateAgainstSGD: 998.4, lastUpdated: '2026-09-24' },
  THB: { code: 'THB', name: 'Thai Baht', symbol: '฿', rateAgainstSGD: 26.8, lastUpdated: '2026-09-24' },
  AUD: { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rateAgainstSGD: 1.142, lastUpdated: '2026-09-24' },
  CHF: { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rateAgainstSGD: 0.655, lastUpdated: '2026-09-24' },
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rateAgainstSGD: 3.32, lastUpdated: '2026-09-24' },
  TWD: { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', rateAgainstSGD: 24.15, lastUpdated: '2026-09-24' },
  VND: { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', rateAgainstSGD: 18750.0, lastUpdated: '2026-09-24' },
  SGD: { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rateAgainstSGD: 1.0, lastUpdated: '2026-09-24' },
};

export const POPULAR_DESTINATIONS: DestinationSummary[] = [
  {
    id: 'tokyo-japan',
    name: 'Tokyo',
    country: 'Japan',
    region: 'East Asia',
    coordinates: [35.6762, 139.6503],
    currencyCode: 'JPY',
    currencySymbol: '¥',
    heroImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    description: 'An electrifying metropolis harmonizing centuries-old shrines, neon skyline districts, Michelin-starred culinary artistry, and tranquil Zen gardens.',
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Shinjuku Gyoen', 'Akihabara', 'Tsukiji Outer Market', 'Meiji Jingu'],
    idealDurationDays: 7,
    costLevel: 'moderate',
    defaultAirport: 'HND / NRT',
  },
  {
    id: 'kyoto-japan',
    name: 'Kyoto',
    country: 'Japan',
    region: 'East Asia',
    coordinates: [35.0116, 135.7681],
    currencyCode: 'JPY',
    currencySymbol: '¥',
    heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    description: 'The cultural soul of Japan with thousands of classical Buddhist temples, gardens, imperial palaces, Shinto shrines, and traditional wooden geisha houses.',
    highlights: ['Fushimi Inari-taisha', 'Kinkaku-ji (Golden Pavilion)', 'Arashiyama Bamboo Grove', 'Gion District', 'Nishiki Market'],
    idealDurationDays: 5,
    costLevel: 'moderate',
    defaultAirport: 'KIX (Osaka Kansai)',
  },
  {
    id: 'paris-france',
    name: 'Paris',
    country: 'France',
    region: 'Western Europe',
    coordinates: [48.8566, 2.3522],
    currencyCode: 'EUR',
    currencySymbol: '€',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    description: 'The City of Light, world capital of art, fashion, gastronomy, and historic architecture along the graceful banks of the Seine.',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Montmartre & Sacré-Cœur', 'Musée d\'Orsay', 'Sainte-Chapelle', 'Le Marais'],
    idealDurationDays: 6,
    costLevel: 'luxury',
    defaultAirport: 'CDG',
  },
  {
    id: 'bali-indonesia',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    coordinates: [-8.3405, 115.092],
    currencyCode: 'IDR',
    currencySymbol: 'Rp',
    heroImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    description: 'Island of the Gods boasting lush volcanic terraces, spiritual cliffside temples, holistic wellness retreats, and vibrant beach sunsets.',
    highlights: ['Ubud Monkey Forest', 'Tegallalang Rice Terraces', 'Uluwatu Temple', 'Tanah Lot', 'Seminyak Coast', 'Mount Batur Sunrise'],
    idealDurationDays: 6,
    costLevel: 'budget',
    defaultAirport: 'DPS (Ngurah Rai)',
  },
  {
    id: 'london-uk',
    name: 'London',
    country: 'United Kingdom',
    region: 'Northern Europe',
    coordinates: [51.5074, -0.1278],
    currencyCode: 'GBP',
    currencySymbol: '£',
    heroImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
    description: 'A global epicenter of history, world-class theatre, free national museums, lush royal parks, and dynamic multicultural food halls.',
    highlights: ['Tower of London', 'British Museum', 'Westminster Abbey', 'Borough Market', 'Hyde Park', 'Covent Garden'],
    idealDurationDays: 6,
    costLevel: 'luxury',
    defaultAirport: 'LHR',
  },
  {
    id: 'seoul-south-korea',
    name: 'Seoul',
    country: 'South Korea',
    region: 'East Asia',
    coordinates: [37.5665, 126.978],
    currencyCode: 'KRW',
    currencySymbol: '₩',
    heroImage: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1200&q=80',
    description: 'A dynamic fusion of centuries-old Joseon royal palaces, bustling night street markets, K-culture districts, and cutting-edge fashion boutiques.',
    highlights: ['Gyeongbokgung Palace', 'Bukchon Hanok Village', 'Myeongdong Shopping', 'Hongdae Indie Culture', 'N Seoul Tower', 'Gwangjang Market'],
    idealDurationDays: 6,
    costLevel: 'moderate',
    defaultAirport: 'ICN',
  },
  {
    id: 'rome-italy',
    name: 'Rome',
    country: 'Italy',
    region: 'Southern Europe',
    coordinates: [41.9028, 12.4964],
    currencyCode: 'EUR',
    currencySymbol: '€',
    heroImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80',
    description: 'The Eternal City, an open-air museum filled with ancient ruins, Renaissance basilicas, vibrant piazzas, and authentic trattorias.',
    highlights: ['Colosseum & Forum', 'Vatican Museums & St. Peter\'s', 'Trevi Fountain', 'Pantheon', 'Piazza Navona', 'Trastevere'],
    idealDurationDays: 5,
    costLevel: 'moderate',
    defaultAirport: 'FCO',
  },
  {
    id: 'zurich-switzerland',
    name: 'Zurich & Swiss Alps',
    country: 'Switzerland',
    region: 'Central Europe',
    coordinates: [47.3769, 8.5417],
    currencyCode: 'CHF',
    currencySymbol: 'CHF',
    heroImage: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&w=1200&q=80',
    description: 'Pristine alpine lakes, charming historic old towns, world-class Swiss chocolate, and gateway to majestic snowcapped peaks.',
    highlights: ['Lake Zurich Promenade', 'Old Town (Altstadt)', 'Uetliberg Mountain', 'Bahnhofstrasse', 'Day Trip to Lucerne & Mount Titlis'],
    idealDurationDays: 7,
    costLevel: 'luxury',
    defaultAirport: 'ZRH',
  },
  {
    id: 'bangkok-thailand',
    name: 'Bangkok',
    country: 'Thailand',
    region: 'Southeast Asia',
    coordinates: [13.7563, 100.5018],
    currencyCode: 'THB',
    currencySymbol: '฿',
    heroImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1200&q=80',
    description: 'A sensory whirlwind of gilded temples, bustling longtail boats along Chao Phraya River, street food stalls, and sprawling modern shopping havens.',
    highlights: ['Grand Palace & Wat Phra Kaew', 'Wat Arun (Temple of Dawn)', 'Chatuchak Weekend Market', 'Chinatown (Yaowarat)', 'IconSiam'],
    idealDurationDays: 4,
    costLevel: 'budget',
    defaultAirport: 'BKK / DMK',
  },
  {
    id: 'sydney-australia',
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    coordinates: [-33.8688, 151.2093],
    currencyCode: 'AUD',
    currencySymbol: 'A$',
    heroImage: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80',
    description: 'Spectacular sun-drenched harbor city celebrated for its iconic architectural marvels, world-class coastal walks, and relaxed beachside cafe culture.',
    highlights: ['Sydney Opera House', 'Sydney Harbour Bridge Climb', 'Bondi to Coogee Coastal Walk', 'The Rocks Historic Precinct', 'Taronga Zoo'],
    idealDurationDays: 6,
    costLevel: 'luxury',
    defaultAirport: 'SYD',
  },
  {
    id: 'new-york-usa',
    name: 'New York City',
    country: 'United States',
    region: 'North America',
    coordinates: [40.7128, -74.006],
    currencyCode: 'USD',
    currencySymbol: '$',
    heroImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1200&q=80',
    description: 'The energetic city that never sleeps, offering iconic Broadway shows, landmark skyscrapers, sprawling Central Park, and diverse boroughs.',
    highlights: ['Central Park', 'Empire State Building', 'Statue of Liberty & Ellis Island', 'High Line & Chelsea', 'Times Square', 'Metropolitan Museum of Art'],
    idealDurationDays: 6,
    costLevel: 'luxury',
    defaultAirport: 'JFK / EWR',
  },
  {
    id: 'reykjavik-iceland',
    name: 'Reykjavik',
    country: 'Iceland',
    region: 'Northern Europe',
    coordinates: [64.1466, -21.9426],
    currencyCode: 'EUR',
    currencySymbol: '€',
    heroImage: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200&q=80',
    description: 'Gateway to surreal volcanic landscapes, cascading glacial waterfalls, geothermal lagoons, black sand beaches, and magical Northern Lights.',
    highlights: ['Blue Lagoon Geothermal Spa', 'Golden Circle Route', 'Hallgrímskirkja Church', 'Black Sand Beach (Reynisfjara)', 'Gullfoss Waterfall'],
    idealDurationDays: 7,
    costLevel: 'luxury',
    defaultAirport: 'KEF',
  },
];

export const DESTINATION_DETAILS_MAP: Record<
  string,
  {
    visa: VisaInfo;
    factoids: DestinationFactoids;
    weather: Record<string, WeatherSeasonInfo>;
    flightsFromSIN: FlightOption[];
    groundTransport: GroundTransportOption[];
    accommodations: AccommodationOption[];
    places: PlaceActivity[];
  }
> = {
  'tokyo-japan': {
    visa: {
      destinationCountry: 'Japan',
      passportCountry: 'Singapore (🇸🇬)',
      visaRequired: false,
      visaType: 'Visa-Free Exemption (Biometric / ICAO Compliant Passport)',
      maxStayDays: 90,
      passportValidityMonths: 6,
      requiredDocuments: ['Valid Passport (at least 6 months validity)', 'Return or onward flight ticket', 'Visit Japan Web digital customs/immigration QR code'],
      electronicArrivalCardRequired: true,
      arrivalCardName: 'Visit Japan Web (Fast Track Immigration & Customs QR)',
      notes: 'Singapore passport holders enjoy 90 days visa-free for tourism. Complete the online Visit Japan Web registration before departure for fast-track immigration arrival.',
      healthRequirements: ['No mandatory vaccinations for standard travel'],
      provider: 'Open Travel & Visa MCP (Singapore MFA & Japan MOFA verified)',
    },
    factoids: {
      destinationName: 'Tokyo',
      country: 'Japan',
      tagline: 'Where ancient traditions and futuristic innovation coexist seamlessly.',
      historySnippet: 'Originally a tranquil fishing hamlet named Edo, the city became the seat of the Tokugawa Shogunate in 1603 before being renamed Tokyo ("Eastern Capital") in 1868.',
      culturalEtiquette: [
        'Bow gently when greeting or thanking people; handshakes are also widely accepted.',
        'Keep voice volume down in trains and never talk on phone calls on public transit.',
        'Stand on the left side of escalators in Tokyo (right side in Osaka/Kyoto) to allow people in a rush to pass.',
        'Carry a small pouch for trash, as public bins are rare; streets are kept exceptionally clean.',
        'Never stick chopsticks vertically into rice bowls (associated with Buddhist funeral rituals).',
      ],
      diningCustoms: [
        'Slurping ramen and soba noodles is considered a compliment to the chef and aerates the flavors.',
        'Say "Itadakimasu" before eating and "Gochisousama deshita" when finishing.',
        'Many traditional restaurants request shoe removal at the entryway; wear clean socks.',
      ],
      tippingPolicy: 'Strictly No Tipping: Tipping is not customary in Japan and may cause confusion or polite refusal. Outstanding service is naturally included.',
      localPhrases: [
        { phrase: 'Arigatou gozaimasu', translation: 'Thank you very much', pronunciation: 'Ah-ree-gah-toh goh-zah-ee-mahs' },
        { phrase: 'Sumimasen', translation: 'Excuse me / Sorry', pronunciation: 'Soo-mee-mah-sen' },
        { phrase: 'Kore o kudasai', translation: 'Please give me this one', pronunciation: 'Koh-reh oh koo-dah-sah-ee' },
        { phrase: 'O-kaikei onegaishimasu', translation: 'Bill please', pronunciation: 'Oh-kah-ee-kay oh-neh-gah-ee-shee-mahs' },
        { phrase: 'Eigo ga hanasemasu ka?', translation: 'Do you speak English?', pronunciation: 'Ay-goh gah hah-nah-seh-mahs kah?' },
      ],
      emergencyNumbers: { police: '110', ambulance: '119', touristHelp: '050-3816-2787 (JNTO Tourist Hotline)' },
      plugTypes: ['Type A (2 flat pins, 100V)', 'Type B (3 pins, 100V) - Singapore 3-pin adapter needed'],
      waterDrinkable: true,
      provider: 'Travel Factoids & Culture MCP',
    },
    weather: {
      default: {
        destination: 'Tokyo',
        month: 'November',
        averageTempC: 12,
        highTempC: 17,
        lowTempC: 8,
        rainfallDays: 5,
        condition: 'Crisp, sunny autumn with peak red-maple foliage (Koyo)',
        clothingTips: ['Layered clothing (trench coat or light wool jacket)', 'Comfortable walking sneakers (15,000+ steps daily)', 'Light scarf for cool evenings', 'Heattech undershirts for night outings'],
        bestSeasonVerdict: 'Prime Travel Window: November is among the best months to visit Tokyo, offering crisp blue skies, low humidity, and breathtaking autumn leaf colors.',
        provider: 'Open-Meteo & Climate Data MCP',
      },
    },
    flightsFromSIN: [
      {
        id: 'fl-sq-634',
        airline: 'Singapore Airlines',
        flightNumber: 'SQ 634',
        originAirport: 'SIN (Changi T3)',
        destinationAirport: 'HND (Tokyo Haneda)',
        departureTime: '13:55 (SIN)',
        arrivalTime: '21:50 (HND)',
        duration: '6h 55m',
        stops: 0,
        priceSGD: 780,
        priceLocal: 89115,
        currency: 'JPY',
        baggage: '25kg Checked + 7kg Cabin',
        carbonKg: 285,
        provider: 'Open Flight Routes & Schedule MCP',
      },
      {
        id: 'fl-nh-844',
        airline: 'All Nippon Airways (ANA)',
        flightNumber: 'NH 844',
        originAirport: 'SIN (Changi T2)',
        destinationAirport: 'HND (Tokyo Haneda)',
        departureTime: '22:20 (SIN)',
        arrivalTime: '06:00 (+1 HND)',
        duration: '6h 40m',
        stops: 0,
        priceSGD: 840,
        priceLocal: 95970,
        currency: 'JPY',
        baggage: '2x 23kg Checked + 10kg Cabin',
        carbonKg: 270,
        provider: 'Open Flight Routes & Schedule MCP',
      },
      {
        id: 'fl-tr-808',
        airline: 'Scoot',
        flightNumber: 'TR 808',
        originAirport: 'SIN (Changi T1)',
        destinationAirport: 'NRT (Tokyo Narita)',
        departureTime: '01:10 (SIN)',
        arrivalTime: '08:55 (NRT)',
        duration: '6h 45m',
        stops: 0,
        priceSGD: 450,
        priceLocal: 51412,
        currency: 'JPY',
        baggage: 'Cabin 10kg (Baggage Add-on: SGD 65)',
        carbonKg: 290,
        provider: 'Open Flight Routes & Schedule MCP',
      },
      {
        id: 'fl-jl-036',
        airline: 'Japan Airlines (JAL)',
        flightNumber: 'JL 036',
        originAirport: 'SIN (Changi T1)',
        destinationAirport: 'HND (Tokyo Haneda)',
        departureTime: '21:50 (SIN)',
        arrivalTime: '05:35 (+1 HND)',
        duration: '6h 45m',
        stops: 0,
        priceSGD: 820,
        priceLocal: 93685,
        currency: 'JPY',
        baggage: '2x 23kg Checked + 10kg Cabin',
        carbonKg: 275,
        provider: 'Open Flight Routes & Schedule MCP',
      },
    ],
    groundTransport: [
      {
        id: 'gt-tokyo-shinkansen',
        type: 'high_speed_rail',
        name: 'Tokaido Shinkansen (Nozomi Bullet Train)',
        route: 'Tokyo Station ➔ Shin-Osaka / Kyoto',
        duration: '2h 15m',
        frequency: 'Every 10-15 minutes',
        priceSGD: 125,
        priceLocal: 14280,
        currency: 'JPY',
        operator: 'JR Central',
        notes: 'World-famous 285 km/h high-speed rail. Reserved seats recommended during peak morning departures.',
        provider: 'Open Transit & Rail Routing MCP',
      },
      {
        id: 'gt-narita-express',
        type: 'express_train',
        name: 'Narita Express (N\'EX)',
        route: 'Narita Airport (NRT) ➔ Tokyo / Shinjuku / Shibuya',
        duration: '54 mins to Tokyo Stn',
        frequency: 'Every 30 minutes',
        priceSGD: 28,
        priceLocal: 3200,
        currency: 'JPY',
        operator: 'JR East',
        notes: 'Comfortable dedicated luggage storage, free Wi-Fi, round-trip discount tickets available.',
        provider: 'Open Transit & Rail Routing MCP',
      },
      {
        id: 'gt-tokyo-subway-pass',
        type: 'metro',
        name: 'Tokyo Subway 72-Hour Pass',
        route: 'Unlimited rides on all Tokyo Metro & Toei Subway lines',
        duration: '72 consecutive hours',
        frequency: 'Every 2-4 minutes',
        priceSGD: 13,
        priceLocal: 1500,
        currency: 'JPY',
        operator: 'Tokyo Metro & Toei',
        notes: 'Massive savings compared to IC card fares for tourists exploring across central wards.',
        provider: 'Open Transit & Rail Routing MCP',
      },
    ],
    accommodations: [
      {
        id: 'acc-tokyo-1',
        name: 'Hotel Groove Shinjuku, A Parkroyal Hotel',
        type: 'hotel',
        rating: 4.7,
        reviewsCount: 1420,
        pricePerNightSGD: 290,
        pricePerNightLocal: 33132,
        currency: 'JPY',
        totalNights: 7,
        totalSGD: 2030,
        location: 'Kabukicho, Shinjuku, Tokyo',
        neighborhood: 'Shinjuku (Walking distance to JR Shinjuku Station & Omoide Yokocho)',
        coordinates: [35.6953, 139.7024],
        amenities: ['Panoramic Sky Views', 'Direct Airport Limousine Bus Stop', 'High-speed Wi-Fi', 'On-site Cocktail Lounge', 'Luggage Courier Service'],
        imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        description: 'Chic modern hotel occupying upper floors of the Tokyu Kabukicho Tower, offering awe-inspiring skyline vistas, soundproofed rooms, and unbeatable dining access.',
        provider: 'Open Accommodations & Stays MCP',
      },
      {
        id: 'acc-tokyo-2',
        name: 'The Blossom Hibiya (Ginza / Hibiya)',
        type: 'boutique',
        rating: 4.8,
        reviewsCount: 980,
        pricePerNightSGD: 340,
        pricePerNightLocal: 38845,
        currency: 'JPY',
        totalNights: 7,
        totalSGD: 2380,
        location: 'Minato / Ginza border, Tokyo',
        neighborhood: 'Ginza & Shimbashi (Close to Imperial Palace gardens and Ginza luxury boutiques)',
        coordinates: [35.6695, 139.7562],
        amenities: ['Spacious 25sqm+ Rooms', 'Breakfast with Japanese-Western Buffet', 'Bathtubs with skyline views', 'Nespresso Coffee Machine', 'Quiet soundproofing'],
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        description: 'Upscale retreat perched between Ginza and Hibiya Park. Known for gracious hospitality, large floor-to-ceiling windows, and effortless transit links.',
        provider: 'Open Accommodations & Stays MCP',
      },
      {
        id: 'acc-tokyo-3',
        name: 'Candeo Hotels Tokyo Shimbashi',
        type: 'hotel',
        rating: 4.6,
        reviewsCount: 2150,
        pricePerNightSGD: 195,
        pricePerNightLocal: 22278,
        currency: 'JPY',
        totalNights: 7,
        totalSGD: 1365,
        location: 'Shimbashi, Minato, Tokyo',
        neighborhood: 'Shimbashi (3 mins walk to JR Yamanote line & Ginza Line)',
        coordinates: [35.6664, 139.7554],
        amenities: ['Rooftop Sky Spa with Open-Air Onsen Bath', 'Sauna', 'Modern Simmons Beds', 'English-speaking Concierge'],
        imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
        description: 'Exceptional value comfort hotel featuring an open-air rooftop bath and sauna gazing out over Tokyo Tower, perfect after long days of walking.',
        provider: 'Open Accommodations & Stays MCP',
      },
      {
        id: 'acc-tokyo-4',
        name: 'Mimaru Tokyo Station East (Family / Apartment)',
        type: 'apartment',
        rating: 4.7,
        reviewsCount: 760,
        pricePerNightSGD: 310,
        pricePerNightLocal: 35417,
        currency: 'JPY',
        totalNights: 7,
        totalSGD: 2170,
        location: 'Chuo Ward, near Tokyo Station',
        neighborhood: 'Nihombashi / Hatchobori (Quiet residential corner with direct train access)',
        coordinates: [35.6795, 139.7795],
        amenities: ['Full Kitchenette with Stove & Microwave', 'Dining Table', 'Coin Laundry in building', 'Separate Shower & Washroom'],
        imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
        description: 'Spacious apartment-style stay equipped with kitchen facilities, ideal for couples or families wanting a homey base without frequent hotel changes.',
        provider: 'Open Accommodations & Stays MCP',
      },
    ],
    places: [
      {
        id: 'plc-meiji-jingu',
        name: 'Meiji Jingu & Yoyogi Forest',
        category: 'culture',
        rating: 4.8,
        reviewsCount: 45000,
        estimatedDuration: '2 hours',
        costSGD: 0,
        costLocal: 0,
        currency: 'JPY',
        coordinates: [35.6764, 139.6993],
        address: '1-1 Yoyogikamizonocho, Shibuya City, Tokyo',
        openingHours: 'Sunrise to Sunset (06:00 - 16:30 in Nov)',
        imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=800&q=80',
        description: 'Majestic Shinto shrine nestled in a serene 170-acre evergreen forest of 120,000 trees donated by people across Japan in 1920.',
        insiderTip: 'Visit early around 8:00 AM before tour groups arrive. Watch for traditional Shinto wedding processions on weekend mornings.',
        factoid: 'The massive entrance Torii gate is constructed from 1,500-year-old Taiwanese cypress wood.',
        tags: ['Free Entry', 'Serene', 'Spiritual', 'Nature Walk'],
        provider: 'Open Places & OSM MCP',
      },
      {
        id: 'plc-shibuya-sky',
        name: 'Shibuya Sky Observatory',
        category: 'sightseeing',
        rating: 4.8,
        reviewsCount: 18500,
        estimatedDuration: '1.5 hours',
        costSGD: 22,
        costLocal: 2500,
        currency: 'JPY',
        coordinates: [35.6585, 139.7013],
        address: '2-24-12 Shibuya, Shibuya City, Tokyo',
        openingHours: '10:00 - 22:30 (Last entry 21:20)',
        imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
        description: 'Breathtaking 360-degree open-air rooftop observation deck perched 229 meters above Shibuya Crossing, boasting uninterrupted views toward Mount Fuji on clear days.',
        insiderTip: 'Sunset slots (approx 16:30 in November) sell out weeks in advance; book online 4 weeks early.',
        factoid: 'The observation floor has an open hammock net area where visitors can gaze directly into the sky.',
        tags: ['Iconic View', 'Mount Fuji View', 'Photography'],
        provider: 'Open Places & OSM MCP',
      },
      {
        id: 'plc-senso-ji',
        name: 'Senso-ji Temple & Nakamise-dori',
        category: 'culture',
        rating: 4.7,
        reviewsCount: 68000,
        estimatedDuration: '2 hours',
        costSGD: 0,
        costLocal: 0,
        currency: 'JPY',
        coordinates: [35.7148, 139.7967],
        address: '2-3-1 Asakusa, Taito City, Tokyo',
        openingHours: 'Main Hall: 06:00 - 17:00 (Grounds open 24/7)',
        imageUrl: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=800&q=80',
        description: 'Tokyo’s oldest Buddhist temple founded in 645 AD, famed for its massive Kaminarimon (Thunder Gate) red lantern and historic shopping alley.',
        insiderTip: 'Return after 19:30 for the dramatic pagoda illumination with zero crowds.',
        factoid: 'The giant paper lantern hanging at Kaminarimon weighs over 700 kilograms.',
        tags: ['Historic', 'Cultural Landmark', 'Street Food Snack'],
        provider: 'Open Places & OSM MCP',
      },
      {
        id: 'plc-tsukiji-outer',
        name: 'Tsukiji Outer Market Food Crawl',
        category: 'food',
        rating: 4.6,
        reviewsCount: 32000,
        estimatedDuration: '2.5 hours',
        costSGD: 35,
        costLocal: 4000,
        currency: 'JPY',
        coordinates: [35.6655, 139.7708],
        address: '4-16-2 Tsukiji, Chuo City, Tokyo',
        openingHours: '08:00 - 14:00 (Best 08:30 - 11:30, closed Wednesdays & Sundays)',
        imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
        description: 'Bustling foodie haven of over 400 stalls selling fresh sashimi rice bowls, wagyu beef skewers, tamagoyaki (sweet rolled omelets), and grilled king crab.',
        insiderTip: 'Eat food at designated standing counter areas near stalls; walking while eating is discouraged on the street.',
        factoid: 'Even after the wholesale auction moved to Toyosu in 2018, Tsukiji remains the premier culinary street hub.',
        tags: ['Must-Eat', 'Seafood', 'Street Food', 'Breakfast'],
        provider: 'Open Places & OSM MCP',
      },
      {
        id: 'plc-teamlab-planets',
        name: 'teamLab Planets TOKYO (DMM)',
        category: 'entertainment',
        rating: 4.8,
        reviewsCount: 29000,
        estimatedDuration: '2 hours',
        costSGD: 34,
        costLocal: 3880,
        currency: 'JPY',
        coordinates: [35.6517, 139.7915],
        address: '6-1-16 Toyosu, Koto City, Tokyo',
        openingHours: '09:00 - 22:00 (Advance reservation mandatory)',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
        description: 'Immersive sensory museum where visitors walk barefoot through water filled with swimming digital koi fish and wander through an endless crystal mirror universe.',
        insiderTip: 'Wear pants that can be rolled above knee height as you walk through knee-deep warm water.',
        factoid: 'The exhibits respond to visitor movements in real time using algorithmic generative code.',
        tags: ['Immersive Art', 'Sensory', 'Photography'],
        provider: 'Open Places & OSM MCP',
      },
      {
        id: 'plc-shinjuku-gyoen',
        name: 'Shinjuku Gyoen National Garden',
        category: 'nature',
        rating: 4.7,
        reviewsCount: 39000,
        estimatedDuration: '2 hours',
        costSGD: 4.5,
        costLocal: 500,
        currency: 'JPY',
        coordinates: [35.6852, 139.71],
        address: '11 Naitomachi, Shinjuku City, Tokyo',
        openingHours: '09:00 - 16:30 (Closed Mondays)',
        imageUrl: 'https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=800&q=80',
        description: 'Stunning 144-acre former imperial estate blending traditional Japanese landscaping with French Formal and English Landscape gardens.',
        insiderTip: 'Alcohol is strictly forbidden at the entry gates, making it a peaceful and impeccably quiet haven.',
        factoid: 'In autumn, the park displays the imperial Chrysanthemum flower exhibition in traditional thatched pavilions.',
        tags: ['Autumn Foliage', 'Quiet Nature', 'Botanical'],
        provider: 'Open Places & OSM MCP',
      },
    ],
  },
  'paris-france': {
    visa: {
      destinationCountry: 'France (Schengen Area)',
      passportCountry: 'Singapore (🇸🇬)',
      visaRequired: false,
      visaType: 'Schengen Visa-Free Exemption (Up to 90 days in any 180-day period)',
      maxStayDays: 90,
      passportValidityMonths: 3, // 3 months beyond intended departure
      requiredDocuments: ['Valid Passport (valid for 3+ months past departure)', 'Proof of accommodation', 'Proof of sufficient travel funds (approx €65/day)', 'Return or onward flight ticket', 'Travel insurance covering min €30,000 medical expenses recommended'],
      electronicArrivalCardRequired: false,
      arrivalCardName: 'ETIAS (European Travel Information & Authorisation System starting mid-2025/2026)',
      notes: 'Singapore citizens can visit France and the Schengen zone visa-free for tourism or business up to 90 days in any 180-day window.',
      healthRequirements: ['Standard routine vaccinations'],
      provider: 'Open Travel & Visa MCP (Singapore MFA & EU Schengen verified)',
    },
    factoids: {
      destinationName: 'Paris',
      country: 'France',
      tagline: 'The timeless City of Light, celebrated for high fashion, cuisine, and romantic boulevards.',
      historySnippet: 'Founded around the 3rd century BC by the Parisii Celtic tribe on the Île de la Cité, Paris grew into the dazzling heart of the French Enlightenment and global arts.',
      culturalEtiquette: [
        'Always greet shopkeepers and waiters with "Bonjour, Madame" or "Bonjour, Monsieur" when entering; not greeting is considered rude.',
        'Keep your voice at a moderate tone in cafes, restaurants, and the Metro.',
        'Bread is placed directly on the tablecloth or plate edge, never on the main plate.',
      ],
      diningCustoms: [
        'Lunch is typically 12:30 - 14:00; dinner begins after 19:30 or 20:00.',
        'Water ("une carafe d\'eau") and bread are provided free of charge at dining establishments.',
      ],
      tippingPolicy: 'Service Compris: A 15% service charge is already included by French law in the bill. Rounding up or leaving €1 to €3 in coins for attentive table service is customary.',
      localPhrases: [
        { phrase: 'Bonjour', translation: 'Hello / Good morning', pronunciation: 'Bon-zhoor' },
        { phrase: 'S\'il vous plaît', translation: 'Please', pronunciation: 'Seel voo play' },
        { phrase: 'Merci beaucoup', translation: 'Thank you very much', pronunciation: 'Mair-see boh-koo' },
        { phrase: 'L\'addition, s\'il vous plaît', translation: 'The bill please', pronunciation: 'Lah-dee-syohn seel voo play' },
        { phrase: 'Parlez-vous anglais ?', translation: 'Do you speak English?', pronunciation: 'Par-lay voo ahn-glay?' },
      ],
      emergencyNumbers: { police: '17', ambulance: '15', touristHelp: '112 (European Emergency Number)' },
      plugTypes: ['Type C / Type E (2 round pins, 230V) - Singapore adapter needed'],
      waterDrinkable: true,
      provider: 'Travel Factoids & Culture MCP',
    },
    weather: {
      default: {
        destination: 'Paris',
        month: 'November',
        averageTempC: 8,
        highTempC: 11,
        lowTempC: 5,
        rainfallDays: 9,
        condition: 'Atmospheric autumn chill with golden tree-lined boulevards and occasional light drizzle',
        clothingTips: ['Warm wool overcoat or trench coat', 'Cashmere or merino wool sweater', 'Sturdy water-resistant leather walking boots', 'Compact umbrella and stylish scarf'],
        bestSeasonVerdict: 'Cozy and romantic shoulder season with dramatically shorter queues at major museums and romantic bistro dining.',
        provider: 'Open-Meteo & Climate Data MCP',
      },
    },
    flightsFromSIN: [
      {
        id: 'fl-sq-336',
        airline: 'Singapore Airlines',
        flightNumber: 'SQ 336',
        originAirport: 'SIN (Changi T3)',
        destinationAirport: 'CDG (Paris Charles de Gaulle T1)',
        departureTime: '00:15 (SIN)',
        arrivalTime: '07:15 (CDG)',
        duration: '14h 00m',
        stops: 0,
        priceSGD: 1180,
        priceLocal: 816,
        currency: 'EUR',
        baggage: '25kg Checked + 7kg Cabin',
        carbonKg: 520,
        provider: 'Open Flight Routes & Schedule MCP',
      },
      {
        id: 'fl-af-181',
        airline: 'Air France',
        flightNumber: 'AF 181',
        originAirport: 'SIN (Changi T1)',
        destinationAirport: 'CDG (Paris Charles de Gaulle T2E)',
        departureTime: '23:35 (SIN)',
        arrivalTime: '06:50 (+1 CDG)',
        duration: '14h 15m',
        stops: 0,
        priceSGD: 1090,
        priceLocal: 754,
        currency: 'EUR',
        baggage: '23kg Checked + 12kg Cabin',
        carbonKg: 510,
        provider: 'Open Flight Routes & Schedule MCP',
      },
      {
        id: 'fl-qr-947',
        airline: 'Qatar Airways (1-Stop DOH)',
        flightNumber: 'QR 947 ➔ QR 039',
        originAirport: 'SIN (Changi T1)',
        destinationAirport: 'CDG (Paris CDG)',
        departureTime: '20:45 (SIN)',
        arrivalTime: '06:30 (+1 CDG)',
        duration: '15h 45m (1h 50m layover in Doha)',
        stops: 1,
        stopDetails: 'Doha Hamad Intl (DOH)',
        priceSGD: 860,
        priceLocal: 595,
        currency: 'EUR',
        baggage: '25kg Checked + 7kg Cabin',
        carbonKg: 495,
        provider: 'Open Flight Routes & Schedule MCP',
      },
    ],
    groundTransport: [
      {
        id: 'gt-rer-b',
        type: 'express_train',
        name: 'RER B Regional Train',
        route: 'CDG Airport ➔ Gare du Nord / Châtelet-Les Halles',
        duration: '35 minutes',
        frequency: 'Every 10-15 minutes',
        priceSGD: 16.5,
        priceLocal: 11.45,
        currency: 'EUR',
        operator: 'RATP / SNCF',
        notes: 'Direct connection from airport terminals into central Paris Metro hubs.',
        provider: 'Open Transit & Rail Routing MCP',
      },
      {
        id: 'gt-tgv-inoui',
        type: 'high_speed_rail',
        name: 'TGV inOUI High-Speed Rail',
        route: 'Paris Gare de Lyon ➔ Lyon / Marseille / Nice / Switzerland',
        duration: '1h 57m to Lyon',
        frequency: 'Every 30 minutes',
        priceSGD: 75,
        priceLocal: 52,
        currency: 'EUR',
        operator: 'SNCF',
        notes: 'High-speed trains cruising at 320 km/h with comfortable power sockets and onboard bistro car.',
        provider: 'Open Transit & Rail Routing MCP',
      },
    ],
    accommodations: [
      {
        id: 'acc-paris-1',
        name: 'Hôtel Le Relais Saint-Germain (Saint-Germain-des-Prés)',
        type: 'boutique',
        rating: 4.8,
        reviewsCount: 650,
        pricePerNightSGD: 390,
        pricePerNightLocal: 270,
        currency: 'EUR',
        totalNights: 6,
        totalSGD: 2340,
        location: '6th Arrondissement, Left Bank, Paris',
        neighborhood: 'Saint-Germain-des-Prés (Steps from Luxembourg Gardens & historic literary cafes)',
        coordinates: [48.8524, 2.3387],
        amenities: ['Artisan French Breakfast Included', 'Historic 17th-century Beams', 'Designer Toile de Jouy Linens', 'Hermès Toiletries'],
        imageUrl: 'https://images.unsplash.com/photo-1549294413-26f195200c16?auto=format&fit=crop&w=800&q=80',
        description: 'Charming boutique hotel on the Left Bank exuding quintessential Parisian romance and literary history, with direct access to gourmet bistro Yves Camdeborde.',
        provider: 'Open Accommodations & Stays MCP',
      },
      {
        id: 'acc-paris-2',
        name: 'CitizenM Paris Gare de Lyon',
        type: 'hotel',
        rating: 4.6,
        reviewsCount: 3800,
        pricePerNightSGD: 215,
        pricePerNightLocal: 148,
        currency: 'EUR',
        totalNights: 6,
        totalSGD: 1290,
        location: '12th Arrondissement, Paris',
        neighborhood: 'Gare de Lyon / Bastille (5 mins walk to Seine river & trendy Bastille cafes)',
        coordinates: [48.8447, 2.3734],
        amenities: ['Panoramic 16th-floor CloudM Rooftop Bar', 'MoodPad Room Controls', 'Ultra-comfortable XL King Bed', '24/7 CanteenM'],
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        description: 'Smart contemporary hotel featuring clever design, floor-to-ceiling city views, and stellar cocktail lounge overlooking the Seine.',
        provider: 'Open Accommodations & Stays MCP',
      },
    ],
    places: [
      {
        id: 'plc-louvre',
        name: 'Musée du Louvre & Tuileries Garden',
        category: 'culture',
        rating: 4.8,
        reviewsCount: 130000,
        estimatedDuration: '3.5 hours',
        costSGD: 32,
        costLocal: 22,
        currency: 'EUR',
        coordinates: [48.8606, 2.3376],
        address: 'Rue de Rivoli, 75001 Paris',
        openingHours: '09:00 - 18:00 (Wed & Fri open until 21:00, closed Tuesdays)',
        imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
        description: 'The world’s largest art museum, home to the Mona Lisa, Venus de Milo, and Winged Victory of Samothrace inside a historic royal palace.',
        insiderTip: 'Enter via the Carrousel du Louvre underground mall entrance rather than the outdoor pyramid to avoid long security queues.',
        factoid: 'If you spent 30 seconds viewing each of the 380,000 objects in the Louvre, it would take you roughly 100 days straight.',
        tags: ['Must-Visit', 'Art & History', 'Architectural Icon'],
        provider: 'Open Places & OSM MCP',
      },
      {
        id: 'plc-eiffel-tower',
        name: 'Eiffel Tower & Champ de Mars',
        category: 'sightseeing',
        rating: 4.7,
        reviewsCount: 155000,
        estimatedDuration: '2.5 hours',
        costSGD: 42,
        costLocal: 29.4,
        currency: 'EUR',
        coordinates: [48.8584, 2.2945],
        address: 'Champ de Mars, 5 Av. Anatole France, 75007 Paris',
        openingHours: '09:30 - 23:45',
        imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=800&q=80',
        description: 'Gustave Eiffel’s wrought-iron lattice masterpiece soaring 330 meters above the Seine river, sparkling with 20,000 golden lights every hour on the hour after dusk.',
        insiderTip: 'Book summit tickets exactly 60 days in advance online. For photo spots without crowds, head to Passerelle Debilly footbridge.',
        factoid: 'The tower shrinks by up to 15 centimeters during winter due to thermal contraction of the puddle iron.',
        tags: ['World Wonder', 'Panoramic Views', 'Night Illumination'],
        provider: 'Open Places & OSM MCP',
      },
      {
        id: 'plc-montmartre',
        name: 'Montmartre & Sacré-Cœur Basilica',
        category: 'culture',
        rating: 4.8,
        reviewsCount: 88000,
        estimatedDuration: '2.5 hours',
        costSGD: 0,
        costLocal: 0,
        currency: 'EUR',
        coordinates: [48.8867, 2.3431],
        address: '35 Rue du Chevalier de la Barre, 75018 Paris',
        openingHours: '06:30 - 22:30 (Free Entry)',
        imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
        description: 'Bohemian hilltop village that inspired Picasso, Renoir, and Van Gogh, crowned by the radiant travertine domes of the Sacré-Cœur with grand panoramic city views.',
        insiderTip: 'Wander past the crowd at Place du Tertre toward Rue de l\'Abreuvoir and the historic Montmartre Vineyard (Clos Montmartre).',
        factoid: 'The basilica’s travertine stone secretes calcite when it rains, keeping the exterior naturally gleaming white.',
        tags: ['Bohemian', 'Panoramic View', 'Historic Streetscape'],
        provider: 'Open Places & OSM MCP',
      },
    ],
  },
};

// Generates dynamic data for any searched destination worldwide
export function generateGenericDestinationDetails(destName: string): {
  destination: DestinationSummary;
  visa: VisaInfo;
  factoids: DestinationFactoids;
  weather: WeatherSeasonInfo;
  flights: FlightOption[];
  groundTransport: GroundTransportOption[];
  accommodations: AccommodationOption[];
  places: PlaceActivity[];
} {
  const norm = destName.toLowerCase().trim();
  const matched = POPULAR_DESTINATIONS.find((d) => d.name.toLowerCase().includes(norm) || norm.includes(d.name.toLowerCase()));
  const name = matched ? matched.name : destName;
  const country = matched ? matched.country : 'International';
  const currencyCode = matched ? matched.currencyCode : 'USD';
  const currency = GLOBAL_CURRENCY_RATES[currencyCode] || GLOBAL_CURRENCY_RATES['USD'];
  const coords: [number, number] = matched ? matched.coordinates : [35.6762, 139.6503];

  const destination: DestinationSummary = matched || {
    id: `dest-${norm.replace(/\s+/g, '-')}`,
    name,
    country,
    region: 'Global',
    coordinates: coords,
    currencyCode: currency.code,
    currencySymbol: currency.symbol,
    heroImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80',
    description: `Captivating global destination in ${country} offering distinct cultural heritage, regional cuisine, and remarkable landmarks.`,
    highlights: ['Historic District & Old Town', 'Iconic Landmark & Viewpoint', 'Local Market & Gastronomy', 'Scenic Nature & Waterfront'],
    idealDurationDays: 6,
    costLevel: 'moderate',
    defaultAirport: 'Major International Airport',
  };

  const visa: VisaInfo = {
    destinationCountry: country,
    passportCountry: 'Singapore (🇸🇬)',
    visaRequired: false,
    visaType: 'Visa-Free / Electronic Authorisation',
    maxStayDays: 90,
    passportValidityMonths: 6,
    requiredDocuments: ['Valid Passport (6+ months validity)', 'Return or onward ticket', 'Proof of accommodation'],
    electronicArrivalCardRequired: false,
    notes: 'Singapore passport holders enjoy visa-free or straightforward electronic entry to most major leisure travel destinations.',
    healthRequirements: ['Routine travel vaccinations recommended'],
    provider: 'Open Visa & Border MCP',
  };

  const factoids: DestinationFactoids = {
    destinationName: name,
    country,
    tagline: `Experience the authentic essence and hospitality of ${name}.`,
    historySnippet: `${name} has long served as a vibrant crossroads of commerce, culture, and architecture within ${country}.`,
    culturalEtiquette: [
      'Show respect for local heritage, cultural sites, and religious customs.',
      'A polite greeting in the local tongue is always warmly welcomed by residents.',
      'Check local dress codes when entering sacred or historic buildings.',
    ],
    diningCustoms: [
      'Seek out neighborhood eateries frequented by locals for the most authentic flavors.',
      'Always clarify dietary restrictions (e.g. vegetarian, halal) when ordering.',
    ],
    tippingPolicy: 'Standard international hospitality practice: check local guidelines or round up the bill for courteous service.',
    localPhrases: [
      { phrase: 'Hello', translation: 'Greetings', pronunciation: 'Standard' },
      { phrase: 'Thank you', translation: 'Expression of gratitude', pronunciation: 'Standard' },
      { phrase: 'How much is this?', translation: 'Cost inquiry', pronunciation: 'Standard' },
      { phrase: 'Check please', translation: 'Bill request', pronunciation: 'Standard' },
    ],
    emergencyNumbers: { police: '112', ambulance: '112', touristHelp: 'Local Tourist Info Office' },
    plugTypes: ['Standard international voltage (220-240V or 110V)'],
    waterDrinkable: true,
    provider: 'Travel Factoids & Culture MCP',
  };

  const weather: WeatherSeasonInfo = {
    destination: name,
    month: 'Upcoming Season',
    averageTempC: 18,
    highTempC: 23,
    lowTempC: 14,
    rainfallDays: 6,
    condition: 'Pleasant and comfortable for sightseeing and outdoor excursions',
    clothingTips: ['Breathable layers', 'Light windbreaker or light coat for evenings', 'Supportive walking shoes'],
    bestSeasonVerdict: 'Favorable travel season with pleasant daytime temperatures.',
    provider: 'Open-Meteo & Climate Data MCP',
  };

  const flights: FlightOption[] = [
    {
      id: `fl-std-1`,
      airline: 'Singapore Airlines',
      flightNumber: 'SQ 822',
      originAirport: 'SIN (Changi)',
      destinationAirport: `${name} Intl`,
      departureTime: '10:30 (SIN)',
      arrivalTime: '17:45 (Local)',
      duration: '7h 15m',
      stops: 0,
      priceSGD: 720,
      priceLocal: Math.round(720 * currency.rateAgainstSGD),
      currency: currency.code,
      baggage: '25kg Checked + 7kg Cabin',
      carbonKg: 310,
      provider: 'Open Flight Routes & Schedule MCP',
    },
    {
      id: `fl-std-2`,
      airline: 'Regional Flag Carrier',
      flightNumber: 'RC 402',
      originAirport: 'SIN (Changi)',
      destinationAirport: `${name} Intl`,
      departureTime: '23:15 (SIN)',
      arrivalTime: '06:30 (+1 Local)',
      duration: '7h 15m',
      stops: 0,
      priceSGD: 580,
      priceLocal: Math.round(580 * currency.rateAgainstSGD),
      currency: currency.code,
      baggage: '20kg Checked + 7kg Cabin',
      carbonKg: 295,
      provider: 'Open Flight Routes & Schedule MCP',
    },
  ];

  const groundTransport: GroundTransportOption[] = [
    {
      id: `gt-1`,
      type: 'express_train',
      name: 'Airport Express Link',
      route: `${name} Airport ➔ Central Hub`,
      duration: '35 minutes',
      frequency: 'Every 15 minutes',
      priceSGD: 18,
      priceLocal: Math.round(18 * currency.rateAgainstSGD),
      currency: currency.code,
      operator: 'National Railway / Transit',
      notes: 'Direct transit from airport terminal to city center.',
      provider: 'Open Transit & Rail Routing MCP',
    },
    {
      id: `gt-2`,
      type: 'metro',
      name: 'City Transit Multi-Day Pass',
      route: 'Citywide Metro & Bus Network',
      duration: 'Unlimited travel',
      frequency: 'Every 3-5 minutes',
      priceSGD: 12,
      priceLocal: Math.round(12 * currency.rateAgainstSGD),
      currency: currency.code,
      operator: 'Metropolitan Transit Authority',
      notes: 'Convenient contactless pass for city exploration.',
      provider: 'Open Transit & Rail Routing MCP',
    },
  ];

  const accommodations: AccommodationOption[] = [
    {
      id: `acc-gen-1`,
      name: `Grand Central ${name} Hotel`,
      type: 'hotel',
      rating: 4.7,
      reviewsCount: 1280,
      pricePerNightSGD: 240,
      pricePerNightLocal: Math.round(240 * currency.rateAgainstSGD),
      currency: currency.code,
      totalNights: 6,
      totalSGD: 1440,
      location: `Central District, ${name}`,
      neighborhood: 'Downtown City Center',
      coordinates: [coords[0] + 0.005, coords[1] + 0.004],
      amenities: ['Buffet Breakfast', 'Free High-speed Wi-Fi', 'Fitness Center', 'Luggage Storage'],
      imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      description: `Well-appointed 4-star hotel in the heart of ${name}, within walking distance of key transit and dining streets.`,
      provider: 'Open Accommodations & Stays MCP',
    },
    {
      id: `acc-gen-2`,
      name: `The Artisan Boutique Suites`,
      type: 'boutique',
      rating: 4.8,
      reviewsCount: 640,
      pricePerNightSGD: 290,
      pricePerNightLocal: Math.round(290 * currency.rateAgainstSGD),
      currency: currency.code,
      totalNights: 6,
      totalSGD: 1740,
      location: `Historic Arts Quarter, ${name}`,
      neighborhood: 'Old Town Heritage Area',
      coordinates: [coords[0] - 0.006, coords[1] - 0.005],
      amenities: ['Artisan Coffee Bar', 'Courtyard Garden', 'Soundproof Rooms', 'Designer Decor'],
      imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
      description: `Intimate boutique hotel filled with local artistry, personalized service, and serene courtyard ambience.`,
      provider: 'Open Accommodations & Stays MCP',
    },
  ];

  const places: PlaceActivity[] = [
    {
      id: `plc-gen-1`,
      name: `${name} Historic Old Town & Heritage Square`,
      category: 'culture',
      rating: 4.8,
      reviewsCount: 14200,
      estimatedDuration: '2.5 hours',
      costSGD: 0,
      costLocal: 0,
      currency: currency.code,
      coordinates: coords,
      address: `Central Heritage District, ${name}`,
      openingHours: 'Open daily, best visited 09:00 - 18:00',
      imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
      description: `The historic heart of ${name}, featuring preserved architecture, charming pedestrian alleys, and street cafes.`,
      insiderTip: 'Start early in the morning to enjoy the cobblestone streets before walking tours arrive.',
      factoid: `Preserved for centuries as the civic and cultural focal point of ${name}.`,
      tags: ['Free Entry', 'Historic', 'Culture Walk'],
      provider: 'Open Places & OSM MCP',
    },
    {
      id: `plc-gen-2`,
      name: `${name} Panoramic Viewpoint & Sky Deck`,
      category: 'sightseeing',
      rating: 4.7,
      reviewsCount: 9800,
      estimatedDuration: '1.5 hours',
      costSGD: 22,
      costLocal: Math.round(22 * currency.rateAgainstSGD),
      currency: currency.code,
      coordinates: [coords[0] + 0.012, coords[1] + 0.01],
      address: `Sky Tower Boulevard, ${name}`,
      openingHours: '10:00 - 22:00',
      imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
      description: `Grand observation deck offering 360-degree vistas across the entire skyline, bay, and surrounding hills.`,
      insiderTip: 'Arrive 45 minutes prior to sunset for day-to-night lighting transitions.',
      tags: ['Panoramic View', 'Photography'],
      provider: 'Open Places & OSM MCP',
    },
    {
      id: `plc-gen-3`,
      name: `Grand Central Food Market`,
      category: 'food',
      rating: 4.6,
      reviewsCount: 18500,
      estimatedDuration: '2 hours',
      costSGD: 25,
      costLocal: Math.round(25 * currency.rateAgainstSGD),
      currency: currency.code,
      coordinates: [coords[0] - 0.008, coords[1] + 0.007],
      address: `Market Hall Square, ${name}`,
      openingHours: '08:00 - 16:00',
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      description: `Vibrant culinary market with dozens of independent stalls serving local pastries, fresh specialties, cheeses, and artisanal roasted coffees.`,
      insiderTip: 'Look for stalls with lines of local office workers for the freshest dishes.',
      tags: ['Culinary', 'Local Delicacies', 'Market'],
      provider: 'Open Places & OSM MCP',
    },
  ];

  return {
    destination,
    visa,
    factoids,
    weather,
    flights,
    groundTransport,
    accommodations,
    places,
  };
}
