/**
 * Export & Share Itinerary Modal
 */

import React, { useState } from 'react';
import { TripState, VisaInfo, WeatherSeasonInfo } from '../types/travel';
import { Share2, X, Copy, Check, Printer, Download } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  trip: TripState;
  visa: VisaInfo;
  weather: WeatherSeasonInfo;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  trip,
  visa,
  weather,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const totalEstSGD =
    780 * trip.numTravellers +
    280 * Math.max(1, trip.durationDays - 1) +
    65 * trip.durationDays * trip.numTravellers +
    55 * trip.durationDays * trip.numTravellers +
    18 * trip.durationDays * trip.numTravellers +
    350;

  const markdownContent = `# VoyageMCP Travel Itinerary: ${trip.destination.name}, ${trip.destination.country}
**Duration:** ${trip.durationDays} Days | **Travellers:** ${trip.numTravellers} | **Base Budget:** SGD ${trip.baseBudgetSGD.toLocaleString()} (Est. Cost: SGD ${totalEstSGD.toLocaleString()})
**Origin:** Singapore Changi (SIN) ➔ ${trip.destination.defaultAirport}
**Visa Status:** ${visa.visaType} (${visa.maxStayDays} days max stay, ${visa.passportValidityMonths} months validity)
**Weather (${weather.month}):** ${weather.lowTempC}°C - ${weather.highTempC}°C, ${weather.condition}

---

## Day-by-Day Itinerary:
${trip.itinerary
  .map(
    (day) => `
### Day ${day.dayNumber}: ${day.theme} (${day.areaSummary})
Estimated Walking: ~${day.estimatedWalkingKm} km
${day.items
  .map(
    (item, idx) =>
      `${idx + 1}. **${item.startTime} - ${item.endTime}** [${item.timeSlot.toUpperCase()}]: ${item.title} (${item.locationName}) - Est. SGD ${item.estimatedCostSGD}${
        item.notes ? `\n   *Note:* ${item.notes}` : ''
      }`
  )
  .join('\n')}`
  )
  .join('\n\n')}

---
*Generated by VoyageMCP - Universal Open Model Context Protocol Travel Coordinator*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-xs">
      <div className="relative flex max-h-[85vh] w-full max-w-2xl flex-col rounded-2xl border border-slate-700 bg-slate-900 shadow-2xl overflow-hidden">
        <div className="flex items-center justify-between border-b border-slate-800 bg-slate-950 p-4">
          <div className="flex items-center gap-2">
            <Share2 className="h-5 w-5 text-emerald-400" />
            <h3 className="font-bold text-base text-white">Export & Share Travel Itinerary</h3>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-4">
          <textarea
            readOnly
            value={markdownContent}
            rows={15}
            className="w-full rounded-xl border border-slate-800 bg-slate-950 p-4 font-mono text-xs text-slate-300 focus:outline-hidden"
          />
        </div>

        <div className="flex items-center justify-between border-t border-slate-800 bg-slate-950 p-4">
          <span className="text-xs text-slate-400">
            Formatted in Markdown, compatible with Notion, Apple Notes, or WhatsApp.
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-800 px-3 py-2 text-xs font-semibold text-slate-200 hover:bg-slate-700 cursor-pointer"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded-xl bg-emerald-500 px-4 py-2 text-xs font-bold text-slate-950 hover:bg-emerald-400 cursor-pointer"
            >
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
